# Generated by Django 5.0.7 on 2024-07-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_privatechat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.privatechat'),
        ),
        migrations.AddField(
            model_name='message',
            name='public_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publicchat'),
        ),
    ]
