# Generated by Django 5.0.7 on 2024-07-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pokerroom_roomuser_pokerroom_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
